### ISSUE TITLE
Tick/check mark rendering in Firefox

### ISSUE THREAD

**Issue by tjmay1981** [snapappointments/bootstrap-select#2381] opened 2020-01-21 16:09 UTC
The tick that is added using the class `show-tick` doesn't render nicely in Firefox (checked in FF 72 on Windows 10) 
bootstrap-select v1.13.12
jQuery v3.4.1
Bootstrap v4.4.1

To reproduce the problem, open https://plnkr.co/edit/RHA12B5OFfxR2jqg5EEQ?p=preview in Firefox and select an option from the dropdown. The displayed tick is split into three parts by small lines.

This could be remedied by adding the following CSS to the stylesheet.

`.bootstrap-select .bs-ok-default::after {
transform-style: preserve-3d;
}`

**Comment by caseyjhol** [comment] 2020-04-22 17:24
This seems to be fixed in Firefox 75 on Windows 10, but I'll be happy to take another look if you're still having problems.

**Comment by tjmay1981** [comment] 2020-04-24 16:14
I can still reproduce it on my copy of Firefox 75 on Windows 10. Could it
be dependent on screen resolution? Either way my suggested fix resolves the
issue.

[image: image.png]

**Comment by caseyjhol** [comment] 2020-04-24 16:23
Looks like there were some issues with the image you tried to include.

**Comment by tjmay1981** [comment] 2020-04-24 18:08
Sorry, I just replied inline to the email and it obviously doesn't like images being supplied in that way. Hopefully this will work!
![Screenshot_2020-04-24 bootstrap-select playground (Bootstrap 4)](https://user-images.githubusercontent.com/60136222/80243308-eb3e5500-865e-11ea-9a04-7b6069479746.png)

**Comment by caseyjhol** [comment] 2020-04-24 19:20
Thanks! I see what you're talking about (although I'm still unable to reproduce it on my computer). What resolution is your screen? Do you have a retina or 4K display?

**Comment by tjmay1981** [comment] 2020-04-24 19:47
It's nothing special - just a fairly standard 27" Benq GW2760, running at
1920x1080

**Comment by caseyjhol** [comment] 2020-04-24 22:07
I was able to recreate this with a different screen.

**Comment by caseyjhol** [comment] 2020-04-24 22:49
Released in [v1.13.16](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.16)!

**Closed as completed by caseyjhol** 2020-04-24 22:49 UTC
