### ISSUE TITLE
Not working with bootstrap 5

### ISSUE THREAD

**Issue by yurenlimbu** [snapappointments/bootstrap-select#2690] opened 2021-12-16 09:33 UTC
I'm trying to integrate with bootstrap 5 but I not working dropdown with optgroup. Am I missing something? Here is the link https://codepen.io/yurenlimbu/pen/xxXqyoK

**Comment by NicolasCARPi** [comment] 2021-12-16 12:06
Closing as duplicate of https://github.com/snapappointments/bootstrap-select/issues/2607

**Closed as completed by NicolasCARPi** 2021-12-16 12:06 UTC
Labels: bug
