### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by kriit24** [snapappointments/bootstrap-select#2104] opened 2018-09-19 15:52 UTC
Error appears on click in multiple select element, if select is empty.

<div class="dropdown bootstrap-select show-tick show"><select class="selectpicker" name="other_name[]" title="Vali ..." data-on-change="select[name=&quot;user_type[]&quot;]" data-href="/test/trans" data-callback="some" data-selected-text-format="count > 2" multiple="1" tabindex="-98"></select><button type="button" class="btn dropdown-toggle bs-placeholder btn-light" data-toggle="dropdown" role="button" title="Vali ..." aria-expanded="true"><div class="filter-option"><div class="filter-option-inner"><div class="filter-option-inner-inner">Vali ...</div></div> </div></button><div class="dropdown-menu  show" role="combobox" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;"><div class="inner show" role="listbox" aria-expanded="true" tabindex="-1"><ul class="dropdown-menu inner show"></ul></div></div></div>

bootstrap-select.js:2727 Uncaught TypeError: Cannot read property 'className' of undefined
    at c.liHeight (bootstrap-select.js:2727)
    at c.setSize (bootstrap-select.js:2727)
    at HTMLButtonElement.<anonymous> (bootstrap-select.js:2727)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)

**Comment by kriit24** [comment] 2018-09-19 15:53
second click error:

bootstrap-select.js:2727 Uncaught TypeError: Cannot read property 'vert' of undefined
    at c.setMenuSize (bootstrap-select.js:2727)
    at c.setSize (bootstrap-select.js:2727)
    at HTMLButtonElement.<anonymous> (bootstrap-select.js:2727)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)

**Comment by caseyjhol** [comment] 2018-09-19 17:33
Please search next time. Duplicate of #2092.

**Closed as completed by caseyjhol** 2018-09-19 17:33 UTC
