### ISSUE TITLE
selectpicker not working with Knockout.js

### ISSUE THREAD

**Issue by sgodonnell** [snapappointments/bootstrap-select#200] opened 2013-07-07 09:02 UTC
Hi 

I have an app that uses bootstrap-select (selectpicker) for dropdown options. I am using knockout.js to integrate with the server, where a normal <select> works fine:

<select data-bind="options: currencyPairs, optionsText: 'currencyPair'"></select>

The following using bootstrap-select fails:

<select class="selectpicker" data-bind="options: currencyPairs, optionsText: 'currencyPair'"></select>

this comes up as "nothing selected"

Does bootstrap-select support Knockout?

PS the selectpicker works fine as expected without "data-bind" and the knockout code also works fine in the same file.

Any ideas?

**Comment by Rob1080** [comment] 2015-06-11 17:55
I've updated @vincenttheeten fiddle http://jsfiddle.net/bkzb272j/1/ to reference correct bootstrap-select js and css files.

**Comment by pushpapriya** [comment] 2015-07-27 13:39
selectpicker not working in android mobiles APP, my suggestion is changed this css
.bootstrap-select.btn-group .dropdown-menu li {
    position: static;
} 
that is working fine.

**Comment by Sonictherocketman** [comment] 2016-01-21 23:35
Hey everyone. I'm having an issue with using this binding in a template. The view model loads the correct data, but once the template renders, and the bootstrap-select is initialized it overwrites the preexisting value in the select. Any suggestions for a fix?

**Comment by lszomoru** [comment] 2016-02-23 18:08
Has anyone been able to get the custom binding to work with Knockout 3.4? I have looked at it and from the looks of it the root cause of the problem is that ```valueAccessor()();``` returns ```undefined```. I will continue to debug the issue and will circle back to this thread if I find a solution.

**Comment by Bogatinov** [comment] 2016-05-26 12:31
Anyone figured out how to set default value on initialization?
I have come to this http://jsfiddle.net/bkzb272j/226/

Changing the init for the value to 
`ko.bindingHandlers.value.init(element, valueAccessor(), allBindingsAccessor);` works, but then the changes to the observable are not updated.

**Comment by WilliamsDL** [comment] 2016-06-23 15:09
Is there a way to modify this binding to allow optGroups?  I'm having great trouble doing so.

**Comment by DenisPitcher** [comment] 2016-06-23 20:09
Hi Williams,

Here's a copy of my current code, I swear it came from here but who knows.  It should help you with opt groups.

`define([
    'jquery',
    'bootstrap-select',
    'require-css!css/bootstrap/bootstrap-select-1.6.3.min'    
],
    function ($) {

        //// Perhaps try to override the naming of the selector using the code below to change the references as a means around actually modifying the 3rd party files

        //// The following crazy hack is a means to adjust dropdown toggles so that they don't conflict if there is more than one bootstrap library referenced on a page.
        //var documentClickEvents = jQuery._data(document, 'events').click;
        //if (documentClickEvents.length > 0) {
        //    for (var i = 1; i < documentClickEvents.length; i++) {
        //        var e = documentClickEvents[i];
        //        if (e.selector == '[data-toggle=dropdown]') {
        //            e.selector = '[data-toggle=ko-dropdown]'
        //        }
        //        if (e.selector == '[data-toggle="dropdown"]') {
        //            e.selector = '[data-toggle="ko-dropdown"]'
        //        }
                
        //    }
        //}


        // Options Support : https://github.com/knockout/knockout/pull/94#issuecomment-30991262

        //first patch knockout JS to understand optgroups
        ko.bindingHandlers.options.update = function (element, valueAccessor, allBindings) {
            function setTextContent(element, textContent) { //COPY since ko.utils.setTextContent is not exported
                var value = ko.utils.unwrapObservable(textContent);
                if ((value === null) || (value === undefined))
                    value = "";

                // We need there to be exactly one child: a text node.
                // If there are no children, more than one, or if it's not a text node,
                // we'll clear everything and create a single text node.
                var innerTextNode = ko.virtualElements.firstChild(element);
                if (!innerTextNode || innerTextNode.nodeType != 3 || ko.virtualElements.nextSibling(innerTextNode)) {
                    ko.virtualElements.setDomNodeChildren(element, [document.createTextNode(value)]);
                } else {
                    innerTextNode.data = value;
                }

                // Workaround for an IE9 rendering bug - https://github.com/SteveSanderson/knockout/issues/209
                if (ko.utils.ieVersion >= 9) {
                    // For text nodes and comment nodes (most likely virtual elements), we will have to refresh the container
                    var elem = node.nodeType == 1 ? node : node.parentNode;
                    if (elem.style)
                        elem.style.zoom = elem.style.zoom;
                }
            };

            function selectedOptions() {
                return ko.utils.arrayFilter(element.options, function (node) { return node.selected; });
            }

            var selectWasPreviouslyEmpty = element.length == 0;
            var previousScrollTop = (!selectWasPreviouslyEmpty && element.multiple) ? element.scrollTop : null;

            var unwrappedArray = ko.utils.unwrapObservable(valueAccessor());
            var includeDestroyed = allBindings.get('optionsIncludeDestroyed');
            var captionPlaceholder = {};
            var captionValue;
            var previousSelectedValues;
            if (element.multiple) {
                previousSelectedValues = ko.utils.arrayMap(selectedOptions(), ko.selectExtensions.readValue);
            } else {
                previousSelectedValues = element.selectedIndex >= 0 ? [ko.selectExtensions.readValue(element.options[element.selectedIndex])] : [];
            }

            if (unwrappedArray) {
                if (typeof unwrappedArray.length == "undefined") // Coerce single value into array
                    unwrappedArray = [unwrappedArray];

                // Filter out any entries marked as destroyed
                var filteredArray = ko.utils.arrayFilter(unwrappedArray, function (item) {
                    return includeDestroyed || item === undefined || item === null || !ko.utils.unwrapObservable(item['_destroy']);
                });

                // If caption is included, add it to the array
                if (allBindings['has']('optionsCaption')) {
                    captionValue = ko.utils.unwrapObservable(allBindings.get('optionsCaption'));
                    // If caption value is null or undefined, don't show a caption
                    if (captionValue !== null && captionValue !== undefined) {
                        filteredArray.unshift(captionPlaceholder);
                    }
                }
            } else {
                // If a falsy value is provided (e.g. null), we'll simply empty the select element
                unwrappedArray = [];
            }

            function applyToObject(object, predicate, defaultValue) {
                var predicateType = typeof predicate;
                if (predicateType == "function") // Given a function; run it against the data value
                {
                    return predicate(object);
                }
                else if (predicateType == "string") // Given a string; treat it as a property name on the data value
                {
                    if (predicate.indexOf('.') == -1) {
                        return object[predicate];
                    }
                    var arr = predicate.split('.');
                    while (arr.length && (object = object[arr.shift()]));
                    return object;

                }
                else // Given no optionsText arg; use the data value itself
                {
                    return defaultValue;
                }
            }

            // The following functions can run at two different times:
            // The first is when the whole array is being updated directly from this binding handler.
            // The second is when an observable value for a specific array entry is updated.
            // oldOptions will be empty in the first case, but will be filled with the previously generated option in the second.
            var itemUpdate = false;

            function optionForArrayItem(arrayEntry, index, oldOptions) {
                if (oldOptions.length) {
                    previousSelectedValues = oldOptions[0].selected ? [ko.selectExtensions.readValue(oldOptions[0])] : [];
                    itemUpdate = true;
                }
                var option = document.createElement("option");
                if (arrayEntry === captionPlaceholder) {
                    setTextContent(option, allBindings.get('optionsCaption'));
                    ko.selectExtensions.writeValue(option, undefined);
                } else {
                    // Apply a value to the option element
                    var optionValue = applyToObject(arrayEntry, allBindings.get('optionsValue'), arrayEntry);
                    ko.selectExtensions.writeValue(option, ko.utils.unwrapObservable(optionValue));

                    // Apply some text to the option element
                    var optionText = applyToObject(arrayEntry, allBindings.get('optionsText'), optionValue);
                    setTextContent(option, optionText);
                }
                return [option];
            }

            function optionGroupForArrayItem(arrayEntry) {
                if (arrayEntry === captionPlaceholder) {
                    return optionForArrayItem.apply(this, arguments);
                }

                var optgroup = document.createElement("optgroup");
                var optGroupItems = applyToObject(arrayEntry, allBindings.get('optgroupChildren'), []);

                ko.utils.setDomNodeChildrenFromArrayMapping(optgroup, ko.utils.unwrapObservable(optGroupItems), optionForArrayItem);
                // Apply some text to the optgroup element
                var optgroupText = applyToObject(arrayEntry, allBindings.get('optgroupText'), arrayEntry);
                optgroup.setAttribute('label', ko.utils.unwrapObservable(optgroupText));

                return [optgroup];
            }

            function setSelectionCallback(arrayEntry, newOptions) {
                // IE6 doesn't like us to assign selection to OPTION nodes before they're added to the document.
                // That's why we first added them without selection. Now it's time to set the selection.
                if (previousSelectedValues.length) {
                    var isSelected = ko.utils.arrayIndexOf(previousSelectedValues, ko.selectExtensions.readValue(newOptions[0])) >= 0;
                    if (ko.utils.setOptionNodeSelectionState) {
                        ko.utils.setOptionNodeSelectionState(newOptions[0], isSelected);
                    }

                    // If this option was changed from being selected during a single-item update, notify the change
                    if (itemUpdate && !isSelected)
                        ko.dependencyDetection.ignore(ko.utils.triggerEvent, null, [element, "change"]);
                }
            }

            var callback = setSelectionCallback;
            if (allBindings['has']('optionsAfterRender')) {
                callback = function (arrayEntry, newOptions) {
                    setSelectionCallback(arrayEntry, newOptions);
                    ko.dependencyDetection.ignore(allBindings.get('optionsAfterRender'), null, [newOptions[0], arrayEntry !== captionPlaceholder ? arrayEntry : undefined]);
                }
            }

            ko.utils.setDomNodeChildrenFromArrayMapping(element, filteredArray, allBindings.get('optgroupChildren') ? optionGroupForArrayItem : optionForArrayItem, null, callback);

            // Determine if the selection has changed as a result of updating the options list
            var selectionChanged;
            if (element.multiple) {
                // For a multiple-select box, compare the new selection count to the previous one
                // But if nothing was selected before, the selection can't have changed
                selectionChanged = previousSelectedValues.length && selectedOptions().length < previousSelectedValues.length;
            } else {
                // For a single-select box, compare the current value to the previous value
                // But if nothing was selected before or nothing is selected now, just look for a change in selection
                selectionChanged = (previousSelectedValues.length && element.selectedIndex >= 0)
                 ? (ko.selectExtensions.readValue(element.options[element.selectedIndex]) !== previousSelectedValues[0])
                 : (previousSelectedValues.length || element.selectedIndex >= 0);
            }

            // Ensure consistency between model value and selected option.
            // If the dropdown was changed so that selection is no longer the same,
            // notify the value or selectedOptions binding.
            if (selectionChanged && ko.dependencyDetection)
                ko.dependencyDetection.ignore(ko.utils.triggerEvent, null, [element, "change"]);

            // Workaround for IE bug
            // Workaround for IE9 rendering bug - it doesn't reliably display all the text in dynamically-added select boxes unless you force it to re-render by updating the width.
            // (See https://github.com/SteveSanderson/knockout/issues/312, http://stackoverflow.com/questions/5908494/select-only-shows-first-char-of-selected-option)
            // Also fixes IE7 and IE8 bug that causes selects to be zero width if enclosed by 'if' or 'with'. (See issue #839)
            if (ko.utils.ieVersion) {
                var originalWidth = element.style.width;
                element.style.width = 0;
                element.style.width = originalWidth;
            }

            if (previousScrollTop && Math.abs(previousScrollTop - element.scrollTop) > 20)
                element.scrollTop = previousScrollTop;
        };


        ko.bindingHandlers.selectPicker = {
            init: function (element, valueAccessor, allBindingsAccessor) {

                if ($(element).is('select')) {
                    var selectPickerOptions = allBindingsAccessor().selectPickerOptions;
                    if (typeof selectPickerOptions !== 'undefined' && selectPickerOptions !== null) {
                        var options = selectPickerOptions.optionsArray,
                            optionsText = selectPickerOptions.optionsText,
                            optionsValue = selectPickerOptions.optionsValue,
                            optionsCaption = selectPickerOptions.optionsCaption,
                            isDisabled = selectPickerOptions.disabledCondition || false,
                            resetOnDisabled = selectPickerOptions.resetOnDisabled || false,
                            style = selectPickerOptions.style,
                            required = selectPickerOptions.required || false,
                            title = selectPickerOptions.title;

                        
                            
                        if (ko.utils.unwrapObservable(options).length > 0) {
                            // call the default Knockout options binding
                            if (ko.isObservable(options) == false) {
                                options = ko.observableArray(options);
                            }

                            ko.bindingHandlers.options.update(element, options, allBindingsAccessor);
                        }
                        if (isDisabled && resetOnDisabled) {
                            // the dropdown is disabled and we need to reset it to its first option
                            $(element).selectpicker('val', $(element).children('option:first').val());
                        }
                        $(element).prop('disabled', isDisabled);
                        if (style) {
                            $(element).addClass(style).selectpicker('setStyle');
                        }
                        if (title) {
                            $(element).prop('title', title);
                        }
                        if (required === true)
                        {
                            $(element).attr('required', true);
                        }
                    }
                    if (ko.isObservable(valueAccessor())) {
                        if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
                            // in the case of a multiple select where the valueAccessor() is an observableArray, call the default Knockout selectedOptions binding
                            ko.bindingHandlers.selectedOptions.init(element, valueAccessor, allBindingsAccessor);
                        } else {
                            // regular select and observable so call the default value binding
                            ko.bindingHandlers.value.init(element, valueAccessor, allBindingsAccessor);
                        }
                    }
                    $(element).addClass('selectpicker').selectpicker();


                    //var buttons = $(element).parent().find('button');
                    //for (var j =0; j < buttons.length; j++)
                    //{
                    //    var toggle = buttons[j].dataset.toggle;
                    //    if (toggle === "dropdown")
                    //    {
                    //        buttons[j].dataset.toggle = "ko-dropdown";
                    //    }
                    //}

                }
            },
            update: function (element, valueAccessor, allBindingsAccessor) {
                if ($(element).is('select')) {
                    var selectPickerOptions = allBindingsAccessor().selectPickerOptions;
                    if (typeof selectPickerOptions !== 'undefined' && selectPickerOptions !== null) {
                        var options = selectPickerOptions.optionsArray,
                            optionsText = selectPickerOptions.optionsText,
                            optionsValue = selectPickerOptions.optionsValue,
                            optionsCaption = selectPickerOptions.optionsCaption,
                            isDisabled = selectPickerOptions.disabledCondition || false,
                            resetOnDisabled = selectPickerOptions.resetOnDisabled || false,
                            style = selectPickerOptions.style,
                            required = selectPickerOptions.required || false,
                            title = selectPickerOptions.title;
                        if (ko.utils.unwrapObservable(options).length > 0) {
                            // call the default Knockout options binding
                            if (ko.isObservable(options) == false) {
                                options = ko.observableArray(options);
                            }

                            ko.bindingHandlers.options.update(element, options, allBindingsAccessor);
                        }
                        if (isDisabled && resetOnDisabled) {
                            // the dropdown is disabled and we need to reset it to its first option
                            $(element).selectpicker('val', $(element).children('option:first').val());
                        }
                        $(element).prop('disabled', isDisabled);
                        if (style)
                        {
                            $(element).addClass(style).selectpicker('setStyle');
                        }
                        if (title) {
                            $(element).prop('title', title);
                        }
                        if (required === true) {
                            $(element).attr('required', true);
                        }
                    }
                    if (ko.isObservable(valueAccessor())) {
                        if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
                            // in the case of a multiple select where the valueAccessor() is an observableArray, call the default Knockout selectedOptions binding
                            ko.bindingHandlers.selectedOptions.update(element, valueAccessor);
                        } else {
                            // call the default Knockout value binding
                            //ko.bindingHandlers.value.update(element, valueAccessor);
                            element.setAttribute('value', ko.utils.unwrapObservable(valueAccessor()))
                        }
                    }

                    $(element).selectpicker('refresh');
                }
            }
        };
    });`

usage
`data-bind=" selectPicker: selectedInventory,
optionsText: 'name', optionsValue: 'inventoryID',
optgroupChildren: 'inventory', optgroupText: 'category.name',
selectPickerOptions: { optionsArray: model.inventoryGroupedByCategory }" multiple data-selected-text-format="count">`

**Comment by ferencv** [comment] 2017-01-13 07:26
Hi guys,

please why is there the folowing condition in the code?

```
if (ko.utils.unwrapObservable(options).length > 0) {
                        // call the default Knockout options binding
                        ko.bindingHandlers.options.update(element, options, allBindingsAccessor);
                    }
```
I had a problem with setting empty array to selectpicker options dynamicaly, so I had to remove this condition.
Is there any problem that may arise from removing this condition?

**Comment by thiagobruno** [comment] 2017-02-09 09:20
Hi guys,
How to implement the attributes of the options: 
- **data-divider** 
- **data-subtext**
- **data-content**
- ... !

I'm trying to set it here, but it's not correct, I'm not finding the way:


>HTML
```html
<select 
	multiple
	data-bind="
		selectPicker: null, 
		optionsText: 'value',
		optionsDataSubtext : 'subtext', 
		optionsDataDivider : 'divider', 
		optionsValue : 'id', 
		selectPickerOptions: { optionsArray: optionsTest }">
</select>
```

> VIEWMODEL
```javascript
optionsTest = ko.observableArray([
  {id: 1, value: 'A', divider: false, subtext: 'Apple'}, 
  {id: 2, value: 'B', divider: false, subtext: 'Banana'}, 
  {id: null, value: '', divider: true, subtext: ''}, 
  {id: 3, value: 'C', divider: false, subtext: 'Cashew'}, 
  {id: 4, value: 'D', divider: false, subtext: 'Dekopon'}
  ]);
```

> BINDINGHANDLERS
```javascript
ko.bindingHandlers.selectPicker = {
 init: function (element, valueAccessor, allBindingsAccessor) {
   if ($(element).is('select')) {
     if (ko.isObservable(valueAccessor())) {
       if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
         // in the case of a multiple select where the valueAccessor() is an observableArray, call the default Knockout selectedOptions binding
         ko.bindingHandlers.selectedOptions.init(element, valueAccessor, allBindingsAccessor);
       } else {
         // regular select and observable so call the default value binding
         ko.bindingHandlers.value.init(element, valueAccessor, allBindingsAccessor);
       }
     }

     $(element).addClass('selectpicker').selectpicker();
   }
 },
 update: function (element, valueAccessor, allBindingsAccessor, bindingContext) {
   if ($(element).is('select')) {
     var selectPickerOptions = allBindingsAccessor().selectPickerOptions;
     if (typeof selectPickerOptions !== 'undefined' && selectPickerOptions !== null) {
       var options = selectPickerOptions.optionsArray,
           optionsText = selectPickerOptions.optionsText,
           optionsValue = selectPickerOptions.optionsValue,
           optionsCaption = selectPickerOptions.optionsCaption,
           isDisabled = selectPickerOptions.disabledCondition || false,
           resetOnDisabled = selectPickerOptions.resetOnDisabled || false;


       if (ko.utils.unwrapObservable(options).length > 0) {
         // call the default Knockout options binding
         ko.bindingHandlers.options.update(element, options, allBindingsAccessor);
       }
       if (isDisabled && resetOnDisabled) {
         // the dropdown is disabled and we need to reset it to its first option
         $(element).selectpicker('val', $(element).children('option:first').val());
       }
       $(element).prop('disabled', isDisabled);
     }
     if (ko.isObservable(valueAccessor())) {
       if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
         // in the case of a multiple select where the valueAccessor() is an observableArray, call the default Knockout selectedOptions binding
         ko.bindingHandlers.selectedOptions.update(element, valueAccessor);
       } else {
         // call the default Knockout value binding
         ko.bindingHandlers.value.update(element, valueAccessor);
       }
     }

     $(element).selectpicker('refresh');
   }
 }
};
```

Can someone help?

Thank you!

**Comment by robertmclaws** [comment] 2018-11-30 18:18
Just wanted to point out that some of the JSFiddles in here are dramatically out of date. I've updated one of them to the very latest bits (Bootstrap 4.1.3, Knockout 3.5.0, JQuery 3.3.1, Bootstrap-Select 1.13.10) to get it working here: http://jsfiddle.net/0jh31L8z/1/

**Comment by robertmclaws** [comment] 2019-06-04 23:27
Hey Everyone! For anyone still using Knockout, I've had an issue with this Handler for a long time where it worked fine if you were binding to an Observable, but the "selected" option wasn't set, and the value wasn't updated if you were not. So I took a few hours today and fixed it.

```js
ko.bindingHandlers.selectPicker = {
    init: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
        //debugger;
        if ($(element).is('select')) {
            if (ko.isObservable(valueAccessor())) {
                if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
                    // in the case of a multiple select where the valueAccessor() is an observableArray, call the default Knockout selectedOptions binding
                    ko.bindingHandlers.selectedOptions.init(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext);
                } else {
                    // regular select and observable so call the default value binding
                    ko.bindingHandlers.value.init(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext);
                }
            }
            $(element).addClass('selectpicker').selectpicker();
        }
    },
    update: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
        if ($(element).is('select')) {
            var selectPickerOptions = allBindingsAccessor().selectPickerOptions;
            if (typeof selectPickerOptions !== 'undefined' && selectPickerOptions !== null) {
                var optionsList = selectPickerOptions.optionsArray;
                var isDisabled = selectPickerOptions.disabledCondition || false;
                var resetOnDisabled = selectPickerOptions.resetOnDisabled || false;
                var selectedObject = selectPickerOptions.selectedObject;
                var selectedPropertyName = selectPickerOptions.selectedPropertyName;

                // RWM: AllBundingsAccessor has the default Options bindings (Text, Value, Caption) so that binding just works normally.
                ko.bindingHandlers.options.update(element, optionsList, allBindingsAccessor, viewModel, bindingContext);

                if (isDisabled && resetOnDisabled) {
                    // the dropdown is disabled and we need to reset it to its first option
                    $(element).selectpicker('val', $(element).children('option:first').val());
                }
                $(element).prop('disabled', isDisabled);
            }

            if (ko.isObservable(valueAccessor())) {
                if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
                    // in the case of a multiple select where the valueAccessor() is an observableArray, call the default Knockout selectedOptions binding
                    ko.bindingHandlers.selectedOptions.update(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext);
                } else {
                    // call the default Knockout value binding
                    ko.bindingHandlers.value.update(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext);
                }
            //RWM: Need a code path to set the value (and update it) if the value us not Observable.
            } else {
                //RWM: Set the value the first time.
                $(element).selectpicker('val', ko.unwrap(valueAccessor()));

                //RWM: Handle the Changed event to process future updates.
                $(element).on('changed.bs.select', function (e, clickedIndex, isSelected, previousValue, objectToUpdate = selectedObject, propertyToUpdate = selectedPropertyName) {
                    if (!objectToUpdate || !propertyToUpdate) return;
                    objectToUpdate[propertyToUpdate] = $(element).val();
                });
            }

            $(element).selectpicker('refresh');
        }
    }
};
```

This is how you use it in HTML:

```html
<div class="form-group">
    <label for="businessUnit">Business Unit:</label><br />
    <select id="businessUnit" data-width="100%" data-bind="selectPicker: window.viewModel.someObservable().SomeValue, optionsText: 'DisplayName', optionsValue: 'Id', optionsCaption: '-- SELECT ONE --', selectPickerOptions: { optionsArray: $root.yourSourceData, selectedObject: window.viewModel.someObservable(), selectedPropertyName: 'SomeValue' }"></select>
</div>
```

The code will use the "property as string array" support in JavaScript to set value of the object passed in by `selectPickerOptions.selectedObject` every time the `'changed.bs.select'` event is fired.

Now you don't have to manually manipulate Bootstrap Select if you're using Knockout! Hope that helps save someone else a bunch of time.

**Comment by caseyjhol** [comment] 2021-03-27 18:28
This seems like something that would be better handled but a plugin (rather than support by bootstrap-select out of the box). However, I'm open to adding support if it's simple enough; I'm simply not familiar enough with Knockout to know what that would entail. I'm closing this for now, but I'm open to investigating more in the future.

**Closed by caseyjhol** 2021-03-27 18:28 UTC
