### ISSUE TITLE
BootstrapSelect problems with jQueryUI

### ISSUE THREAD

**Issue by joszz** [snapappointments/bootstrap-select#2116] opened 2018-10-15 13:42 UTC
Recently I updated to the latest version of BootstrapSelect (to v1.13.2, coming rfom v1.13.1) and figured out today I was running into issues with jQueryUI resizables.

[I created a CodePen for you to review](https://codepen.io/joszuf/pen/EdXxXj)

The errors will be logged in the browser’s developer console. In the CodePen everything works regardless, in my own project it breaks down more of the project, making the resizable not work anymore.
 It seems that the container option is problematic here.

**Comment by caseyjhol** [comment] 2018-10-15 21:18
Duplicate of #2086.

**Closed as completed by caseyjhol** 2018-10-15 21:18 UTC
