### ISSUE TITLE
multiple select and text format "count > x" doesn't work with 1 or 0 items selected

### ISSUE THREAD

**Issue by GuidoPreite** [snapappointments/bootstrap-select#2515] opened 2020-08-18 14:43 UTC
Bug with the version 1.13.18 (it worked with v1.10.0 that I used on a previous project)

When selecting multiple options the text format is displayed only when there are more than 2 items selected, it used to work when 0 or 1 item is selected with "count > -1" inside the "data-selected-text-format" setting.

this can be fixed by changing the last condition of this line

`showCount = this.multiple && this.options.selectedTextFormat.indexOf('count') !== -1 && selectedCount > 1;`

to -1

`showCount = this.multiple && this.options.selectedTextFormat.indexOf('count') !== -1 && selectedCount > -1;`

**Comment by caseyjhol** [comment] 2020-12-02 01:26
Duplicate of #2367. Please 👍 to vote and subscribe 🔉 for updates.

**Closed as completed by caseyjhol** 2020-12-02 01:26 UTC
Labels: bug
