### ISSUE TITLE
active:hover item has wrong text color since Bootstrap 4.4

### ISSUE THREAD

**Issue by waclaw66** [snapappointments/bootstrap-select#2452] opened 2020-05-02 09:01 UTC
With Bootstrap 4.4.1 the text color is black, using 4.3.1 is white.

https://jsfiddle.net/h5cz3ena/

**Comment by caseyjhol** [comment] 2020-05-02 15:54
Looks like this was introduced here https://github.com/twbs/bootstrap/pull/29140/commits/970c41755a2bdd8f3a4f5dbee039ca7c2dc8b053 (twbs/bootstrap#29140).

Opened an issue to discuss this change and determine best course of action: twbs/bootstrap#30726.

**Comment by caseyjhol** [comment] 2020-05-15 13:05
Confirmed to be an issue with Bootstrap. They merged a fix that will be available next release.

**Closed as completed** 2020-05-15 13:06 UTC
