### ISSUE TITLE
bootstrap-select inside a dropdown-menu

### ISSUE THREAD

**Issue by my-ouZo** [snapappointments/bootstrap-select#2167] opened 2018-12-27 12:11 UTC
Is there a chance to have a bootstrap-select inside a dropdown-menu?
I use stopPropagation() to keep the menu open and data-container="body", but the select-dropdown is not visible.

**Comment by caseyjhol** [comment] 2019-01-15 19:02
Duplicate of #2054. Please search next time.

**Closed as completed by caseyjhol** 2019-01-15 19:02 UTC
