### ISSUE TITLE
Selected text showing outside of dropdown

### ISSUE THREAD

**Issue by go6media** [snapappointments/bootstrap-select#2204] opened 2019-02-27 13:13 UTC
As per attachements. We recently changed to latest CSS / JS version from an old version and now this display error happens with BS selects that have long / large content.  Using latest stable Boot Strap 3

![image](https://user-images.githubusercontent.com/6851754/53492619-2fe95300-3a91-11e9-884f-29eed6866c09.png)

![image](https://user-images.githubusercontent.com/6851754/53492663-54ddc600-3a91-11e9-865e-3d57ea605823.png)

**Comment by caseyjhol** [comment] 2019-02-27 18:26
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by caseyjhol** [comment] 2019-03-08 22:19
Looks to be a duplicate of #2109.

**Closed as completed by caseyjhol** 2019-03-08 22:19 UTC
