### ISSUE TITLE
duplication of options on refresh v1.14.0-beta3

### ISSUE THREAD

**Issue by jayden2** [snapappointments/bootstrap-select#2763] opened 2022-07-20 04:51 UTC
When refreshing the selectpicker options are duplicatied both in the picker dropdown and selected title.
I found the issue whilst toggling disable attribute and then refreshing the picker (.selectpicker('refresh'))

Fiddle of error:
https://jsfiddle.net/jayden2/2t37ez6r/8/

Edit:
This error does not occur in v1.14.0-beta2

**Comment by NicolasCARPi** [comment] 2022-07-22 22:13
Closing as duplicate of #2738

**Closed as completed by NicolasCARPi** 2022-07-22 22:13 UTC
Labels: bug
