### ISSUE TITLE
Get Text That User Types and fill select with dynamic data(from database with ajax)

### ISSUE THREAD

**Issue by m-mohammadi1** [snapappointments/bootstrap-select#2598] opened 2021-04-23 08:51 UTC
Hello Guys I want to get the text that user types in the select and then get the options by ajax from backend (laravel) so How Can I get the text and Then fill the select?

**Comment by scr4bble** [comment] 2023-11-23 19:33
I would like to know the answer to the same question. Anybody having a solution?

**Comment by scr4bble** [comment] 2023-11-23 19:50
I would like to know the answer to the same question. Anybody having a solution?

@caseyjhol is it possible to listen for "search input change" events please?
If not, do you think it would be possible to quickly add this so we can listen for this event?

**Comment by caseyjhol** [comment] 2023-11-24 00:14
Duplicate of https://github.com/snapappointments/bootstrap-select/issues/1305.

Hoping to address this in the final v1.14.0.

**Closed as not planned by caseyjhol** 2023-11-24 00:14 UTC

**Comment by scr4bble** [comment] 2023-11-24 00:35
Thank you for the reference!
Good luck with the release :) this will be a great addition to the tool.
