### ISSUE TITLE
All optgroup show the options listed in the first optgroup

### ISSUE THREAD

**Issue by etoundi2nd** [snapappointments/bootstrap-select#2699] opened 2022-01-13 21:05 UTC
### Code:
```html
        <select class="selectpicker" multiple>
          <optgroup label="African Teams">
            <option>Cameroon</option>
            <option>Egypt</option>
            <option>Ghana</option>
          </optgroup>
          <optgroup label="European Teams">
            <option>Germany</option>
            <option>France</option>
            <option>Italy</option>
          </optgroup>
          <optgroup label="American Teams">
            <option>Brazil</option>
            <option>Argentina</option>
            <option>Colombia</option>
          </optgroup>
        </select>
```

### Rendering:
![Screenshot 2022-01-13 at 22 03 17](https://user-images.githubusercontent.com/19225187/149408782-92c197cf-70b3-454f-adf3-e58e1068bf58.png)

### Branch
https://github.com/snapappointments/bootstrap-select/tree/v1.14.0-beta2

**Comment by NicolasCARPi** [comment] 2022-01-14 21:26
Hello,

Thank you for reporting this issue. Closing as duplicate of https://github.com/snapappointments/bootstrap-select/issues/2607

**Closed as completed by NicolasCARPi** 2022-01-14 21:26 UTC
Labels: bug
