### ISSUE TITLE
Unable to disable auto Dropup 

### ISSUE THREAD

**Issue by khiangte85** [snapappointments/bootstrap-select#2319] opened 2019-08-29 15:32 UTC
I have a problem with disable of auto drop up. I download v.1.13.9 and v.1.13.0, test it locally and set dropupAuto: false but it doesn't work. Then i test again on v.1.12.4 and it works perfectly. There seems to be an issue since  >= 1.13.0.

`$(function(){
  var test = $('#test').selectpicker({
  dropupAuto: false
})`

I have also tried global `$.fn.selectpicker.Constructor.DEFAULTS.dropupAuto = false;` doesn't work either.

<img width="465" alt="Screen Shot 2019-08-28 at 4 46 25 PM" src="https://user-images.githubusercontent.com/8244781/63954123-37210600-caa0-11e9-9001-87fca1ff54a2.png">

**Comment by caseyjhol** [comment] 2019-09-21 21:27
It seems to be working fine for me in my testing. Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by caseyjhol** [comment] 2019-09-24 16:04
Seems like this is probably a duplicate of #2262.

**Closed as completed by caseyjhol** 2019-09-24 16:04 UTC
