### ISSUE TITLE
Can we have Tree view?

### ISSUE THREAD

**Issue by satish5b8** [snapappointments/bootstrap-select#1968] opened 2018-05-03 01:47 UTC
How about adding the tree view inside it?. It would be good if we tree view inside it and we can add properties like canSelectChildren etc...

**Comment by caseyjhol** [comment] 2020-04-21 20:38
Duplicate of #1956. Please 👍 to vote and subscribe 🔉 for updates.

**Closed as completed by caseyjhol** 2020-04-21 20:38 UTC
