### ISSUE TITLE
i18n - Is it available on the latest stable version?

### ISSUE THREAD

**Issue by leonardoayres** [snapappointments/bootstrap-select#2633] opened 2021-07-12 13:59 UTC
Hello,

I'm using the latest stable version (1.13.14) and trying to use the languages files for content translation, but no success so far.

I've tried to set "data-lang" and "data-language" in the **select** tag, but this is ignored completely and to get thing worse, the default language for the version that i've downloaded is "NL".

The i18n feature is available? If yes, how to use it?

All the best.

**Comment by NicolasCARPi** [comment] 2021-07-12 14:08
Duplicate of #2632

**Closed as completed by NicolasCARPi** 2021-07-12 14:08 UTC
Labels: bug
