### ISSUE TITLE
ToolTips On Options

### ISSUE THREAD

**Issue by aday12345** [snapappointments/bootstrap-select#1685] opened 2017-03-23 16:51 UTC
just wondering if it is possible to have tooltips on the options, if so how, I have not been able to get this to work

**Comment by maimaranmurugesan** [comment] 2019-10-11 10:42
Yes it would be very useful and i need this option for sure. If we disable any option we need to show why its been disabled. 
currently I am using bootstrap_select_1_13_4 in this version $el.data('selectpicker').$lis also not available and also we are using virtual scroll option too. 
If you provide this option it will very useful please do the needful. 
Thanks .

**Comment by NicolasCARPi** [comment] 2021-06-04 18:58
Closing as duplicate of https://github.com/snapappointments/bootstrap-select/issues/1830

**Closed by NicolasCARPi** 2021-06-04 18:58 UTC
