### ISSUE TITLE
Select field cannot contain multiline html content after selection

### ISSUE THREAD

**Issue by Joey33** [snapappointments/bootstrap-select#2178] opened 2019-01-13 10:32 UTC
When using data-content attribute on option elements to provide html multiline content
`<option data-content="First line<br>second line">...`
line 2 overflows the field after making a selection.

before selecting:
![screenshot1](http://englishcafe.pl/images/multiline1.png)
after making a selection:
![screenshot2](http://englishcafe.pl/images/multiline2.png)

Using latest versions via cdn - bootstrap 4.1.3, boostrap-select 1.13.2 and latest chrome.

**Comment by caseyjhol** [comment] 2019-02-27 18:28
Duplicate of #2109.

**Closed as completed by caseyjhol** 2019-02-27 18:28 UTC
