### ISSUE TITLE
if title/placeholder enabled, select value changes when pressing back in browser

### ISSUE THREAD

**Issue by Khrysller** [snapappointments/bootstrap-select#1023] opened 2015-05-12 18:00 UTC
Just found an issue with the last master, v1.7.0.

How to replicate: Create a form with some selectboxes, submit the form, press back in the browser to go back to the form. the selectbox highlight the next option instead the option selected.

**Comment by Khrysller** [comment] 2015-05-21 15:33
any thoughts on this? thanks

@caseyjhol

**Comment by caseyjhol** [comment] 2015-05-22 11:41
Any chance you can link me to an example?

**Comment by Khrysller** [comment] 2015-05-27 00:31
@caseyjhol any webpage with a select submiting to another page (or even maybe to the same page), when press back in the browser will select the previous options +1

**Comment by caseyjhol** [comment] 2015-05-27 04:13
It's possible the most recent commit (c09f46cb311d13ae7a840ef04495b0b03ffa89fe) fixed this. Can you give it a try now?

**Comment by Khrysller** [comment] 2015-05-27 22:10
Thanks, you give this a test, tomorrow in the office.

**Comment by Khrysller** [comment] 2015-05-28 11:26
Ok now it is acting even weird:

 - I have a select without the multiple option. But when I check the option, the check do not show and the selected text option do not shows in the select when closed. But it submits.

- Now if I press back in the browser the selects are reseted.

**Comment by caseyjhol** [comment] 2015-05-28 16:58
Can you include some screenshots? I can't recreate this on my end (Windows 8.1, Chrome 43).

**Comment by Khrysller** [comment] 2015-05-31 11:51
I was testing on W7 with IE9. Gonna generate a reduced test case and run it with chrome, ie and firefox on W7

**Comment by Khrysller** [comment] 2015-07-22 14:38
This is still happening in the last dist. I am using W7 and IE9 or last Chrome. How to reproduce:

- Have a page with some selects
- Submit a form
- Press back in form
- The values in the selects get reseted even in the selects with 'selected' pre-defined

**Comment by DarkMerge** [comment] 2015-10-23 11:57
@Khrysller did you solve this problem? I have page with a lot of modal windows, every modal is a form with selectbox. After submitting and press back, html code of <select> is correct. But plugin dont work right.

**Comment by Khrysller** [comment] 2015-11-20 00:16
I am closing this for now. Thanks.

**Comment by vossad01** [comment] 2016-12-30 15:40
If it is indeed the same bug: here is a public site where the issue is easily reproducible: https://index.scala-lang.org/akka/akka/akka-actor

The relevant select is on the right-hand side:
![image](https://cloud.githubusercontent.com/assets/965439/21567661/6ba63da4-ce73-11e6-9146-94236a041008.png)

Steps to reproduce:

1. Got to https://index.scala-lang.org/akka/akka/akka-actor
2. Choose "akka-camel" from the selection box.
3. Note that Statistics, Dependencies, and Dependents sections change (right-hand side)
4. Press Back in the browser
5. Notice that Statistics, Dependencies, and Dependents change back but the selection box still says "akka-camel."

I was using Firefox for when confirming the above.

**Comment by caseyjhol** [comment] 2020-04-30 17:01
I'm able to recreate this, specifically for standard select elements that have the title (placeholder) attribute set. My recreation is more similar to the one described in #1296. The placeholder option is added to the select and automatically selected instead of the default selected value.

**Comment by caseyjhol** [comment] 2020-05-07 22:19
Released in [v1.13.17](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.17)!

**Closed by caseyjhol** 2020-05-07 22:19 UTC
Labels: confirmed, next release
