### ISSUE TITLE
Request: Tags mode display

### ISSUE THREAD

**Issue by AsidStorm** [snapappointments/bootstrap-select#1197] opened 2015-11-05 07:16 UTC
Hello

I have some big select (over 200 items) and want to make multiselect, but there is one problem - unselect something is really big problem, you should find it again and click.

At first i write a solution that works on "change" event of select and draw labels down to select button, but then i realised that it would be a cool solution for this plugin and rewrite it to plugin source.

It looks like this: ![ee17c33835](https://cloud.githubusercontent.com/assets/1109887/10962066/0f06b0b0-83a6-11e5-90f5-1991fe51e589.jpg)

You can click "tag" item to remove it.

Should i add customize options for this "tags" and create pull request? Or this is not realy required feature?

**Comment by caseyjhol** [comment] 2018-09-03 18:01
Duplicate of #565.

**Closed by caseyjhol** 2018-09-03 18:01 UTC
