### ISSUE TITLE
V1.13.10 Selecting non existing option by code breaks the selection

### ISSUE THREAD

**Issue by Jaroost** [snapappointments/bootstrap-select#2303] opened 2019-07-09 06:39 UTC
In Version 1.13.10

Here the bug:

When you select a non existing option by code in select, it breaks the selection by hand:

Here a [code pen](https://codepen.io/anon/pen/WqYama?editors=1111) of the issue.

Here the  v1.13.9 [code pen](https://codepen.io/anon/pen/YoRdVM?editors=1111) working

**Comment by giero** [comment] 2019-07-10 12:14
This bug was also reported here: https://github.com/snapappointments/bootstrap-select/issues/2263

**Comment by caseyjhol** [comment] 2019-08-01 22:34
Duplicate of #2263.

**Closed as completed** 2019-08-01 22:34 UTC
