### ISSUE TITLE
Pre-title when selected

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select#1138] opened 2015-08-28 10:19 UTC
I see you can specify a title, when nothing is being selected, so it would show something like:

`Please select an item`

But is it possible to add a pre-title, so that when an item is being selected, it would show:

`Selected: Item`

...instead of just:

`Item`

Thanks!

**Comment by NicolasCARPi** [comment] 2021-05-29 15:10
@caseyjhol this can be closed as duplicate of #898

**Closed** 2021-05-30 13:51 UTC
