### ISSUE TITLE
Creating a vanilla JS version

### ISSUE THREAD

**Issue by fabiochelly** [snapappointments/bootstrap-select#2291] opened 2019-06-08 13:27 UTC
Is it possible to create a Vanilla JS version? It would be a lot faster and as Bootstrap 5 will be pure Vanilla, it would be important  to follow the flow.

Is there a lot of work to convert this plugin to a simple JS object? I can help.

**Comment by caseyjhol** [comment] 2019-06-18 21:37
It's certainly possible. Right now, most of our limitations come from our attempt to support versions of IE < 11. See https://github.com/snapappointments/bootstrap-select/issues/2228#issuecomment-476328158 for more info.

**Comment by fabiochelly** [comment] 2019-06-19 19:17
I tried to understand your code but it is huge. I have a lot of experience converting jquery code to Vanilla JS but can you point out the parts that need to be translated?
Will it be an ES6 version using new "class {...}" implementation?

**Comment by NicolasCARPi** [comment] 2021-06-27 01:30
Closing as duplicate of #2228

**Closed as completed by NicolasCARPi** 2021-06-27 01:30 UTC
