### ISSUE TITLE
When the data exceeds 600, it cannot be displayed normally

### ISSUE THREAD

**Issue by eric-5512** [snapappointments/bootstrap-select#2401] opened 2020-02-21 09:29 UTC
![image](https://user-images.githubusercontent.com/56282991/75021443-5c328680-54cf-11ea-95b1-53620f6d998d.png)

npm-asset/bootstrap-select": "1.13.12

code:

```
<select class="form-control dockInsCompany" name="insCompany">
<option></option>
<?php foreach ($myInscos as $inscoId => $shortName) {?>
    <option <?php if($preQuote['insCompanyId']==$inscoId) echo 'selected' ?> value="<?php echo $inscoId?>"><?php echo $shortName?></option>
<?php } ?>
<optgroup label="">
<?php 
foreach ($inscos as $inscoId => $shortName) { if (empty($myInscos[$inscoId]))  { ?>
    <option <?php if($preQuote['insCompanyId']==$inscoId) echo 'selected' ?> value="<?php echo StringUtil::escape($inscoId) ?>"><?php echo StringUtil::escape($shortName) ?></option>
<?php } } ?>
</optgroup>
</select>

```

**Comment by BT-aestebanez** [comment] 2020-03-09 11:16
I have the same problem (see the video attached)
[test.zip](https://github.com/snapappointments/bootstrap-select/files/4306278/test.zip)

:
In long lists, when we scroll to the bottom of the list and we are almost at the end, everything gets blank and we cannot choose anything.
We are using the searchlive

**Comment by caseyjhol** [comment] 2020-04-15 22:19
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by BT-aestebanez** [comment] 2020-04-16 10:39
Hi,
I cannot reproduce it anymore :)
Thanks
Alvaro

**Comment by caseyjhol** [comment] 2020-04-17 00:21
Closing in favor of #2395.

**Closed as completed by caseyjhol** 2020-04-17 00:21 UTC
