### ISSUE TITLE
How to set the value of a live search field and trigger it

### ISSUE THREAD

**Issue by capegreg** [snapappointments/bootstrap-select#2132] opened 2018-10-31 18:57 UTC
I am grabbing the live search string on the change event and saving it to sessionStorage. I want to later add the text to the search field and run live search. How can this be done? Thanks.

// save selected item text from input
var searchinput = $("#"+$this+":input + button:has(.filter-option-inner-inner)>div>div");
sessionStorage.setItem($this, searchinput.prop("textContent"));

// fetch saved "textContent" and add it to live search input
var inn = $("#"+fld.id+" + button:has(.filter-option-inner-inner)>div>div");
inn.text(textContent);

**Comment by MicahStevens** [comment] 2019-01-24 00:47
I was in a similar situation and my jquery calls to update the search input field were not triggering a search. So after each change, I added:
`$(".searchinput").trigger('propertychange')`
this then would trigger the search function.

**Comment by caseyjhol** [comment] 2019-02-27 18:45
You'll want to follow #1305.

**Comment by rmassa** [comment] 2019-04-25 15:47
How can you read the value of the live search box please ?

**Comment by NicolasCARPi** [comment] 2021-06-27 01:36
Closing as duplicate of #1305

**Closed as completed by NicolasCARPi** 2021-06-27 01:36 UTC
