### ISSUE TITLE
Dropdown skipped on tab - tabindex bug in Safari

### ISSUE THREAD

**Issue by RolandBende** [snapappointments/bootstrap-select#2134] opened 2018-11-01 18:35 UTC
## Bootstrap select dropdown skipped on keyboard tab press in Mac Safari desktop browser

[Video](https://res.cloudinary.com/bwebdesign/video/upload/v1541097122/bootstrap_select_tabindex_bug_in_safari.mov
)

I've tried to add tabindex numbers to the original form select element - did not resolved it.

**Comment by RolandBende** [comment] 2018-11-01 18:36
You can test the form here with Safari:
[LINK](https://partner.privathus.hu/partner-regisztracio)

**Comment by caseyjhol** [comment] 2019-02-13 21:44
Duplicate of #478.

**Closed as completed by caseyjhol** 2019-02-13 21:44 UTC
