### ISSUE TITLE
Title not updating after 'refresh'

### ISSUE THREAD

**Issue by harlet** [snapappointments/bootstrap-select#1456] opened 2016-08-01 10:38 UTC
Hi,
I have this code:

```
var request = $.ajax({
                type: 'POST',
                url: ProjectAPI.url.products,
                data: {_token:token_, id:id },
                beforeSend: function() {
                    selectProducts.html('');
                    selectProducts.attr('title', 'Loading...');
                    selectProducts.prop('disabled', true);
                    selectProducts.selectpicker('refresh');
                }
            });
            request.done(function(data){
                selectProducts.attr('title', 'Choose product...');
                selectProducts.selectpicker('show');
                selectProducts.html(data);
                selectProducts.prop('disabled', false);
                selectProducts.selectpicker('refresh');
            });
```

The title in beforeSend is not refresing/reRender.

**Comment by noamyg** [comment] 2019-08-15 10:15
I know this is an old post but I experience the same issue. I'm using selectpicker with angular's [(ngModel)]. When I'm programmatically  updating the model and then calling `('refresh')`, the selection updates but the title does not.

**Comment by caseyjhol** [comment] 2020-04-22 20:11
Duplicate of #1416. Please 👍 to vote and subscribe 🔉 for updates.

**Closed by caseyjhol** 2020-04-22 20:11 UTC
