### ISSUE TITLE
Javascript exceptions with zero <option>

### ISSUE THREAD

**Issue by PhilPJL** [snapappointments/bootstrap-select#2095] opened 2018-09-07 12:01 UTC
The issue:  If we have a select with no options, when you click on the select when running in the debugger Visual Studio catches some exceptions thrown.  These are apparently ignored but do indicate problems with the code.  We also then see an thin empty dropdown which isn't ideal
![image](https://user-images.githubusercontent.com/271656/45217674-e61b6f00-b29c-11e8-91bb-4e03d0ce11ea.png)

Demo here https://plnkr.co/edit/qXrvcfeBKeGHsydvLGdY?p=preview

Using Jquery 3.3.1,, bootstrap 3.3.7, bootstrap-select 1.13.2

With an enabled select and no items we get an exception here presumably because there are no items and the code is assuming there's at least one.

![image](https://user-images.githubusercontent.com/271656/45217883-a3a66200-b29d-11e8-80ba-1eaf89f8757f.png)

We get a different exception for a disabled select and no items because there isn't any menuPadding info.

![image](https://user-images.githubusercontent.com/271656/45218002-fc75fa80-b29d-11e8-83e6-d38d4ec8cbf1.png)

**Comment by caseyjhol** [comment] 2018-09-07 14:50
Duplicate of #2092. Please search next time.

**Closed as completed by caseyjhol** 2018-09-07 14:50 UTC
