### ISSUE TITLE
Add Label / Header to Dropdown button

### ISSUE THREAD

**Issue by rishitank** [snapappointments/bootstrap-select#1778] opened 2017-08-09 16:00 UTC
Hi,

I was wondering if it were possible to add an optional label or header on the dropdown's button? This is similar to custom content except instead of adding custom content on the options, it would be as a kind of static content on the button (not changing on different selections). For now I've had to do a lot of style hacking using position: absolute to get a label on top of the button which is not ideal. If this is possible, please let me know, otherwise it would be a really useful feature to have. Thanks.

**Comment by JimSaiya** [comment] 2017-08-14 14:57
See issue #1455 -- I'm curious to see if that feature will handle your use case.

**Comment by rishitank** [comment] 2017-08-14 15:24
yes that would be a perfect solution actually if it was implemented.

**Comment by NicolasCARPi** [comment] 2021-06-27 01:50
Closing as duplicate of #1455

**Closed by NicolasCARPi** 2021-06-27 01:50 UTC
