### ISSUE TITLE
Bootstrap Version Option

### ISSUE THREAD

**Issue by mpukit** [snapappointments/bootstrap-select#2106] opened 2018-09-20 17:03 UTC
I bet I'm missing something simple here, but - getting the _"There was an issue retrieving Bootstrap's version. Ensure Bootstrap is being loaded before bootstrap-select and there is no namespace collision"_ warning in the console.

I see that as of version 1.13.2 I can manually specify Bootstrap 4 with "BootstrapVersion":

`$.fn.selectpicker.Constructor.BootstrapVersion = '4';`

Is there an example of where/how this should be declared to clear the message and pick up the correct styling for Bootstrap 4?

**Comment by mpukit** [comment] 2018-09-20 17:11
I am loading Bootstrap asynchronously, fwiw.

**Comment by caseyjhol** [comment] 2018-09-21 04:55
Setting `$.fn.selectpicker.Constructor.BootstrapVersion = '4';` after the bootsrap-select JS should apply the correct classes to work with Bootstrap 4. The warning message in the console will still be there. Loading Bootstrap asynchronously is what's the causing the issue. If setting BootstrapVersion isn't working for you can you link me to an example?

**Comment by russplaysguitar** [comment] 2019-02-16 00:12
From what I can tell, part of the problem is that this module expects Bootstrap to already be available globally. I think it would be better if Bootstrap were defined as a dependency (since there's already a section in the module for defining dependencies using AMD syntax).

**Comment by caseyjhol** [comment] 2019-03-29 16:50
Released in [v1.13.9](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.9)!

**Closed as completed by caseyjhol** 2019-03-29 16:50 UTC
