### ISSUE TITLE
Tooltip bootstrap

### ISSUE THREAD

**Issue by plewasebastian** [snapappointments/bootstrap-select#1497] opened 2016-09-06 13:15 UTC
How to display bootstrap tooltip in bootstrap-select?
If i add data-goggle='tooltip' and data-title='Title' to select with .selectpicker it wont work.
What should I do to make it work?

**Comment by arajadurai69** [comment] 2017-10-11 04:27
Hi @l0pez I am also facing this issue, did you find any solution for this issue?

**Comment by NicolasCARPi** [comment] 2021-06-04 18:58
Closing as duplicate of #1830

**Closed by NicolasCARPi** 2021-06-04 18:58 UTC
