### ISSUE TITLE
Match entire word from list of items when using livesearch

### ISSUE THREAD

**Issue by danielvoicu** [snapappointments/bootstrap-select#1809] opened 2017-09-22 13:13 UTC
Hi,

I'm using bootstrap-select with livesearch, and I was wondering if there's a way to match the exact word. I've tried using "startsWith" and "contains", but because I am using a .json file to show a list of items - also using ajax-bootstrap-select for this - it tends to show the entire list of items, not matter what option I use. So, my question is: what should I do to match an entire word, and not just the characters it starts with or contains?
Thanks!

**Comment by NicolasCARPi** [comment] 2021-06-04 19:07
Duplicate of https://github.com/snapappointments/bootstrap-select/issues/1482

**Closed by NicolasCARPi** 2021-06-04 19:07 UTC
