### ISSUE TITLE
Boostrap-Select has numerous accessibility issues and JS problems

### ISSUE THREAD

**Issue by gabepetersen** [snapappointments/bootstrap-select#2819] opened 2023-02-15 14:21 UTC
I just spent all day trying to fix this component's accessibility, but due to the monolithic JS file for this component, and the disorganization of the JS, I was not able to fix anything effectively. Please separate, refactor, and clean up the JS so we can make effective contributions to this project.

**Comment by NicolasCARPi** [comment] 2023-02-15 16:00
Hello,

I agree with you, and it is probably a result of adding many features over the years without refactoring in-between. The problem is that this project is no longer actively maintained/developed. See:  https://github.com/snapappointments/bootstrap-select/issues/2228#issuecomment-1236207188

>  Please separate, refactor, and clean up the JS 

Please consider that this is a software provided at no charge, and asking maintainers to do heavy work like this is not acceptable, unless you are willing to pay for this, in which case you should say so. Otherwise, I'm closing this issue which brings nothing to the table.

**Closed as completed by NicolasCARPi** 2023-02-15 16:00 UTC
Labels: bug
