### ISSUE TITLE
Keyboard navigation not working when searching and virtualScroll is false

### ISSUE THREAD

**Issue by clausbruun** [snapappointments/bootstrap-select#1219] opened 2015-12-01 15:40 UTC
Reproducible at the demo page: https://developer.snapappointments.com/bootstrap-select/

**Comment by caseyjhol** [comment] 2015-12-01 17:47
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by clausbruun** [comment] 2015-12-02 07:17
I'm not sure why you are closing this? I know that you have many bug reports, but in this case I think its unclear which of the guidelines you refer to. I would appreciate a small comment about this, then I will do my very best to improve the bug report. Thanks in advance.

**Comment by caseyjhol** [comment] 2015-12-02 21:32
Please try it with the most recent version - or at the very least tell me which version of bootstrap-select you are using. When submitting any bug request, regardless of the project, always at least provide the version of the plugin you're using. The version of bootstrap-select on the demo page is not the most current version.

**Comment by iamsid** [comment] 2019-04-05 09:58
Using version 1.13.9. And Bootstrap 4.
When navigating (up/down) with results filtered using search box, console shows following error:
![image](https://user-images.githubusercontent.com/17705415/55619736-f9e96e00-57b6-11e9-9b80-012c546959b6.png)
There is no error when the search filter is empty.

**Comment by caseyjhol** [comment] 2019-04-08 18:47
@iamsid It would be great if you could link me to an example. I'm not able to reproduce this. See https://developer.snapappointments.com/bootstrap-select/playground to get started.

**Comment by caseyjhol** [comment] 2019-04-08 19:54
This is a regression in v1.13.9.

**Comment by caseyjhol** [comment] 2019-04-19 16:04
Released in [v1.13.10](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.10)!

**Closed** 2019-04-19 16:04 UTC
Labels: confirmed, next release
