### ISSUE TITLE
IOS native dropdown not working.

### ISSUE THREAD

**Issue by logicsdrive** [snapappointments/bootstrap-select#2059] opened 2018-08-24 20:11 UTC
IOS native dropdown not working with bootstrap 4 and this beta version of selectpicker. Native dropdown flashes and then hide we can't select any option on mobile.

**Comment by caseyjhol** [comment] 2018-08-25 01:16
What version of iOS are you using? What web browser?

**Comment by logicsdrive** [comment] 2018-08-26 21:06
IOS v 11.4.1
Browser Safari

**Comment by logicsdrive** [comment] 2018-08-29 11:07
@caseyjhol any update?

**Comment by caseyjhol** [comment] 2018-08-29 20:03
Seems to be a duplicate of #1828.

**Closed as completed by caseyjhol** 2018-08-29 20:03 UTC
