### ISSUE TITLE
All optgroup show the options listed in the first optgroup

### ISSUE THREAD

**Issue by HakanKaraoglu** [snapappointments/bootstrap-select#2709] opened 2022-02-14 19:23 UTC
We upgraded our old project (bs3) to bs5.1.3 with a new interface. However, we have some problems with the selection. I am sharing old version and new version. This topic has been opened before, but it was suggested to update the package in general, but it didn't work for me.

We add the data from the service call to the options with the following structure.

```
$.each(obj.data, function (index, item) {
                                if (permissiongroups.indexOf(item.permissiongroup) < 0)
                                    permissiongroups.push(item.permissiongroup);
                            });

                            $.each(permissiongroups, function (ind, permission) {
                                var optgroup = $('<optgroup>');
                                optgroup.attr('label', permission);

                                $.each(obj.data, function (index, item) {
                                    if (permission == item.permissiongroup) {
                                        if (item.selected == true) {
                                            optgroup.append('<option value="' + item.id + '">' + item.name + '</option>');
                                        }
                                        else {
                                            optgroup.append('<option value="' + item.id + '">' + item.name + '</option>');
                                        }
                                    }
                                });
```

Bootstrap version:5.1.3
Bootstrap-Select version: v1.14.0-beta2

Old version :
![image](https://user-images.githubusercontent.com/12962730/153928905-7576aaef-9e19-47fe-a789-a161fb9e5a44.png)

New version:
![image](https://user-images.githubusercontent.com/12962730/153929320-6573816a-2fa7-438c-9c9d-ecf2aa0b6a74.png)

**Comment by San7ro** [comment] 2022-02-15 10:48
Same problem for me 
Bootstrap version: 5.1.3
Bootstrap-Select version: v1.14.0-beta2

**Comment by NicolasCARPi** [comment] 2022-02-15 11:40
Thank you for the report. Closing as duplicate of https://github.com/snapappointments/bootstrap-select/issues/2607

**Closed as completed by NicolasCARPi** 2022-02-15 11:40 UTC
Labels: bug

**Comment by HakanKaraoglu** [comment] 2022-03-19 16:36
Hi @NicolasCARPi,
I prepared an example for you. https://plnkr.co/edit/AVLJvvkMLsfwLmxz 
Try the same example on bs 5.0.1 and you will see it doesn't work. I don't think there is a stable version that works yet. It doesn't work in beta version either. Do you have an idea?
