### ISSUE TITLE
Support HTML in the option title attribute 

### ISSUE THREAD

**Issue by kennysong** [snapappointments/bootstrap-select#2640] opened 2021-08-06 08:30 UTC
First of all, thanks for the fantastic library!

I'm trying to achieve a dropdown that looks like this:

<img width="366" alt="Screen Shot 2021-08-06 at 5 27 42 PM" src="https://user-images.githubusercontent.com/2199875/128481309-8302f813-d13f-4954-8911-1fda9bff3c58.png">

Note the bolded text before the selected option. It's hard to achieve this right now since the [option title attribute](https://developer.snapappointments.com/bootstrap-select/examples/#selected-text) only accepts text, not HTML.

The best workaround I found is to add the bold text in `data-content`, with an extra CSS class `hide-in-dropdown` that hides the bolded text if it's being displayed in the dropdown menu.

```css
.dropdown-menu .hide-in-dropdown {
  display: none;
}
```

This is a little hacky though. Would be great to have built-in support.

**Comment by NicolasCARPi** [comment] 2021-08-07 01:23
Hello, closing it as duplicate of https://github.com/snapappointments/bootstrap-select/issues/2388.

**Closed as completed by NicolasCARPi** 2021-08-07 01:23 UTC
