### ISSUE TITLE
Disable dropupAuto from defaults or from data-attribute not working

### ISSUE THREAD

**Issue by 7iomka** [snapappointments/bootstrap-select#2331] opened 2019-10-02 20:57 UTC
Demo with latest version of this plugin
Scroll to the end of page.
https://codepen.io/7iomka/pen/NWKQOjX?editors=1010

I need to disable global for all instances of plugin dropupAuto.
From documentation, I need to put data-dropup-auto="false" for each instance. It's overhead.
Ok. I go to override defaults. Defaults seems to be changed, but without any effect.

Why?
How to fix that?

**Comment by caseyjhol** [comment] 2019-10-02 22:56
Duplicate of #2262.

**Closed as completed by caseyjhol** 2019-10-02 22:56 UTC
