### ISSUE TITLE
`Uncaught TypeError: Cannot read property '0' of undefined` in bootstrap-select.js:846

### ISSUE THREAD

**Issue by esamo** [snapappointments/bootstrap-select#2203] opened 2019-02-27 12:05 UTC
```
Uncaught TypeError: Cannot read property '0' of undefined
    at scroll (bootstrap-select.js?248117410:846)
    at Selectpicker.createView (bootstrap-select.js?248117410:784)
    at Selectpicker.setSize (bootstrap-select.js?248117410:1732)
    at Selectpicker.refresh (bootstrap-select.js?248117410:2633)
    at HTMLSelectElement.<anonymous> (bootstrap-select.js?248117410:2722)
    at Function.each (jquery-3.3.1.min.js?248117410:2)
    at e.fn.init.each (jquery-3.3.1.min.js?248117410:2)
    at e.fn.init.Plugin [as selectpicker] (bootstrap-select.js?248117410:2702)
    at app_directives.js?248117410:393

scroll | @ | bootstrap-select.js?248117410:846
-- | -- | --
  | createView | @ | bootstrap-select.js?248117410:784
  | setSize | @ | bootstrap-select.js?248117410:1732
  | refresh | @ | bootstrap-select.js?248117410:2633
  | (anonymous) | @ | bootstrap-select.js?248117410:2722
  | each | @ | jquery-3.3.1.min.js?248117410:2
  | each | @ | jquery-3.3.1.min.js?248117410:2
  | Plugin | @ | bootstrap-select.js?248117410:2702
  | (anonymous) | @ | app_directives.js?248117410:393
  | setTimeout (async) |   |  
  | scope.refreshPlugin | @ | app_directives.js?248117410:390
  | (anonymous) | @ | app_directives.js?248117410:395
  | setTimeout (async) |   |  
  | scope.refreshPlugin | @ | app_directives.js?248117410:390
  | $digest | @ | angular.min.js?248117410:151
  | $apply | @ | angular.min.js?248117410:155
  | (anonymous) | @ | angular.min.js?248117410:22
  | invoke | @ | angular.min.js?248117410:45
  | c | @ | angular.min.js?248117410:22
  | Tc | @ | angular.min.js?248117410:22
  | xe | @ | angular.min.js?248117410:21
  | (anonymous) | @ | angular.min.js?248117410:346
  | l | @ | jquery-3.3.1.min.js?248117410:2
  | c | @ | jquery-3.3.1.min.js?248117410:2
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery-3.3.1.min.js?248117410:2
  | u | @ | jquery-3.3.1.min.js?248117410:2
  | fireWith | @ | jquery-3.3.1.min.js?248117410:2
  | fire | @ | jquery-3.3.1.min.js?248117410:2
  | u | @ | jquery-3.3.1.min.js?248117410:2
  | fireWith | @ | jquery-3.3.1.min.js?248117410:2
  | ready | @ | jquery-3.3.1.min.js?248117410:2
  | _ | @ | jquery-3.3.1.min.js?248117410:2
```
Line `that.selectpicker.view.position0 = Math.max(0, chunks[firstChunk][0]) || 0;`
Undefined `chunks[firstChunk]`

App code is just calling `element.selectpicker('refresh')` but I suspect a lot of DOM manipulations is done by angularjs directives and bootstrap-select can't handle the throttle.

---

Bootstrap-select v1.13.3
Chrome v72.0.3626.119

**Comment by esamo** [comment] 2019-02-27 12:49
Also the map file for .min.js to .js is wrong - Chrome shows some comment line at the end like 2727, which makes no sense. I had to use bootstrap-select.js directly to see the proper line.

**Comment by caseyjhol** [comment] 2019-02-27 16:16
Appears to be a duplicate of #2198. Please open a separate issue with more information regarding the map file.

**Closed as completed by caseyjhol** 2019-02-27 16:16 UTC
