### ISSUE TITLE
The "active" option only changes on first keydown, does not update on subsequent keydown events

### ISSUE THREAD

**Issue by yugaego** [snapappointments/bootstrap-select#2425] opened 2020-04-06 14:09 UTC
> Seconded what @Realex-fire says here. Observed behavior of using v1.13.12 in our project has shown that the "active" option only changes on first keydown, does not update on subsequent  keydown events.

_Originally posted by @JPBetley in https://github.com/snapappointments/bootstrap-select/issues/2308#issuecomment-563473534_

I experience the same issue on Mac OS 10.14.6: Safari 13.0.1, Chrome 80.0.3987.149, Firefox 54.

Navigating with a keyboard, only the next moved to option is highlighted. Then highlighting "stucks", until - continuing pressing the same keyboard key - the next round. On a new round, highlighting "moves" one option further. And so on. 

For example:
<img width="593" alt="01-Plunker" src="https://user-images.githubusercontent.com/296460/78566848-81354b80-7828-11ea-86a2-e85f2cd11e88.png">
<img width="693" alt="02-custom" src="https://user-images.githubusercontent.com/296460/78566863-84303c00-7828-11ea-8bbf-794204d26366.png">

Most of the drop-downs are affected in my case. Selects with LiveSearch enabled and without optgroups work as expected.

[Default Plunker install v1.13.12](https://plnkr.co/edit/oBlHQwQBIxTK2HdD) reproduces the issue with the following examples:
  - Large Select (liveSearch disabled)
    - Standard
    - Multiple
  - "Basic" (Live search disabled)
  - multiple, show-menu-arrow, maxOptions=2
  - is-invalid class
  - :invalid/:valid pseudoclass
  - a number of unnamed following examples

**Comment by caseyjhol** [comment] 2020-04-16 23:24
Duplicate of #2308.

**Closed as completed by caseyjhol** 2020-04-16 23:24 UTC
