### ISSUE TITLE
Optgroup - bootstrap 5

### ISSUE THREAD

**Issue by slavikja** [snapappointments/bootstrap-select#2714] opened 2022-03-07 21:37 UTC
Optgroup not working with bootsrtap 5 - i get the same options for each category
<img width="271" alt="image" src="https://user-images.githubusercontent.com/97060967/157121854-de43621e-970a-4292-8fcb-7462bba68386.png">

**Comment by NicolasCARPi** [comment] 2022-03-08 15:05
Closing as duplicate of #2607

**Closed as completed by NicolasCARPi** 2022-03-08 15:05 UTC
Labels: bug
