### ISSUE TITLE
bootstrap-select.js:972 Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by meesha81** [snapappointments/bootstrap-select#2193] opened 2019-02-08 20:34 UTC
Hi,
this error:

bootstrap-select.js:972 Uncaught TypeError: Cannot read property 'classList' of undefined
    at scroll (bootstrap-select.js:972)
    at Selectpicker.createView (bootstrap-select.js:898)
    at Selectpicker.setSize (bootstrap-select.js:1865)
    at Selectpicker.refresh (bootstrap-select.js:2770)
    .....

Caused when we are dynamically reloading options when typing with data-live-search="true".

Selectpicker should have "try/catch" for classList (that's our solution which is working fine). Item where the cursor is can be lost when we are reloading items and that's propably why crash occurs.

This issue is not about "ticked" items, because during dynamic reload of selectpicker options we have to return always all ticked.

Please, can you add some solution (eg as try/catch) that we do not modify manually every new version?

Our "workaround" by simple edit of script (add try/catch):
`             
try {
    active.classList.remove('active');
    if (active.firstChild) active.firstChild.classList.remove('active');
} catch(e) {
}

`

**Comment by caseyjhol** [comment] 2019-02-13 21:00
Duplicate of #2189.

**Closed as completed by caseyjhol** 2019-02-13 21:00 UTC
