### ISSUE TITLE
hasOwnProperty is not a function

### ISSUE THREAD

**Issue by billclinton8** [snapappointments/bootstrap-select#2438] opened 2020-04-18 14:14 UTC
html:
<select #DataCombobox [attr.data-live-search]="true"  ..... ></select>

 for (var dataAttr in dataAttributes) {
		           if (dataAttributes.hasOwnProperty(dataAttr) && $.inArray(dataAttr, DISALLOWED_ATTRIBUTES) !== -1) {
              delete dataAttributes[dataAttr];
            }
			
          }

My HTML reports hasownproperty is not a function in the following JS

**Comment by caseyjhol** [comment] 2020-04-18 15:07
Duplicate of #2430.

**Closed as completed** 2020-04-18 15:07 UTC
