### ISSUE TITLE
In Internet Explorer, with liveSearchPlaceholder enabled, can't select option while searchBox is focused. Also, selected option doesn't get scrolled to when opening menu

### ISSUE THREAD

**Issue by BrianH824** [snapappointments/bootstrap-select#2402] opened 2020-02-25 21:54 UTC
My drop downs work fine in Google Chrome, but if the list is long enough that there is a vertical scroll bar and the drop down is scrolled in IE, the moment an item is selected the drop down closes and the item is not selected. I am using IE 11, JQuery 3.4.1, Bootstrap 4.3.1, and Bootstrap-select 1.13.12. I've only seen this issue in IE.

**Comment by BrianH824** [comment] 2020-02-26 16:48
Additionally, I've found that this only occurs when using the live search functionality on the drop down.

**Comment by caseyjhol** [comment] 2020-05-07 23:43
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with your link.

**Comment by DrorOzgaon** [comment] 2020-05-20 20:40
Hello,

I have the same issue on my end. The actual bug comes from the "data-live-search-placeholder" attribute - it will not allow any items that need to be scrolled to, to be selected. It will also not display the value provided in the attribute.

You can easily reproduce the issue by just adding the following attribute to the plankr you provided:
data-live-search-placeholder="search..."
See the first dropdown here: https://plnkr.co/edit/8st1t3YhCElaJhLg

The obvious workaround for this is to remove the "data-live-search-placeholder" attribute for the time being.

**Comment by caseyjhol** [comment] 2020-05-21 00:02
Thanks for the Plunker. It looks like the option is able to be selected if you drag the scrollbar (causing the input to lose focus); it also doesn't scroll to the selected option when you re-open the menu (in IE11).

**Comment by caseyjhol** [comment] 2020-05-21 00:22
This is happening because IE is incorrectly firing an `input` event when the searchbox is focused (if the searchbox has a `placeholder` attribute).

https://stackoverflow.com/questions/48138865/ie-11-text-input-with-placeholder-triggering-input-event-on-focus

**Comment by caseyjhol** [comment] 2020-06-26 18:06
Released in [v1.13.18](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.18)!

**Closed as completed by caseyjhol** 2020-06-26 18:06 UTC
