### ISSUE TITLE
Live search with Ajax to populate options. Is it possible?

### ISSUE THREAD

**Issue by lulibo** [snapappointments/bootstrap-select#2416] opened 2020-03-29 10:33 UTC
Hi!
I'm wondering if there is a way to have the live search with Ajax in order to populate options. 
In other words, when a user start typing in the search box, an ajax call start and return new options.

Is there a quick way?
If not, what you would suggest? Is it ok to just update the option list and force the render method?
$('.selectpicker').selectpicker('render');

Thank you for your help.
Luca

**Comment by caseyjhol** [comment] 2020-04-15 22:18
Duplicate of #899. Please 👍 and follow to keep track of updates. In the meantime, check out https://github.com/truckingsim/Ajax-Bootstrap-Select.

**Closed as completed by caseyjhol** 2020-04-15 22:18 UTC
