### ISSUE TITLE
(de)select all buttons rendered too small

### ISSUE THREAD

**Issue by MichaelMerkel** [snapappointments/bootstrap-select#1294] opened 2016-02-15 14:37 UTC
hi.

when i use a selectpicker with the width set to _data-width="fit"_ and the select button is quite narrow the select all/deselect all buttons are too small to fit the text in them. see attached screenshot.
i'd suggest to set a min-width in that case - if the buttons are displayed.

thanks and regards
michael
![screenshot](https://cloud.githubusercontent.com/assets/17252901/13051547/0118faf4-d3fa-11e5-8c51-1ffcfd9d8902.png)

**Comment by cmizer** [comment] 2016-03-24 16:48
I'm having the same issue. I've added a css fix as a workaround.

.bs-actionsbox { min-width:200px;}

**Comment by sofiyastrochyk** [comment] 2016-07-11 14:44
+1, i'm also using `data-width="fit"` and `data-actions-box="true"` and this happens every time when options contain short text.
It would be really nice to see a solution other than setting `min-width`, since i'm also using translations instead of default "Select All"/"Deselect All" text, and it's not guaranteed that hardcoded `min-width` of button would fit the text.

**Comment by NicolasCARPi** [comment] 2021-06-04 18:16
Closing as duplicate of https://github.com/snapappointments/bootstrap-select/issues/1958 which contains a workaround.

**Closed by NicolasCARPi** 2021-06-04 18:16 UTC
